# Generated by Django 4.1.2 on 2022-10-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blog Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-date"],
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["-date"],
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolio Profiles",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill", name="name", field=models.CharField(max_length=300),
        ),
    ]
