# Generated by Django 4.1.2 on 2022-10-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_userprofile_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="skill", name="is_key_skill",),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.CharField(default="NA", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skill", name="image", field=models.CharField(max_length=30),
        ),
    ]
