# Generated by Django 4.1.2 on 2022-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_blog_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactprofile",
            name="subject",
            field=models.TextField(default="a", verbose_name="Subject"),
            preserve_default=False,
        ),
    ]
